flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: config
      paths:
        - packages/config/
      carryforward: true
    - name: foxify
      paths:
        - packages/foxify/
      carryforward: true
    - name: fresh
      paths:
        - packages/fresh/
      carryforward: true
    - name: http
      paths:
        - packages/http/
      carryforward: true
    - name: inject
      paths:
        - packages/inject/
      carryforward: true
