flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: false
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: foxify
      paths:
        - packages/foxify/
      carryforward: false
