packages:
  # all packages in direct subdirectories of benchmarks/
  - 'benchmarks/*'
  # all packages in direct subdirectories of examples/
  - 'examples/*'
  # all packages in direct subdirectories of packages/
  - 'packages/*'
