name: Nx Test CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11
    with:
      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="test" --agent-count=3
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
        pnpm exec nx-cloud record -- pnpm exec nx format:check
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=3
        pnpm exec nx affected --target=build --parallel=3
        pnpm exec nx affected --target=test --parallel=3 -- --coverage --ci --verbose
      number-of-agents: 2

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
    with:
      number-of-agents: 2
