# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        node-version: [ 14.x ]

    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Use PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      - run: pnpm i
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,NODE_VERSION
          fail_ci_if_error: true
