name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    with:
      main-branch-name: main
      number-of-agents: 3
      node-version: 16
      pnpm-version: 8
      artifacts-name: coverage
      artifacts-path: packages/*/coverage/**
      init-commands: |
        pnpm nx-cloud start-ci-run --stop-agents-after test --agent-count 3
      parallel-commands-on-agents: |
        pnpm nx affected -t lint --parallel 2
        pnpm nx affected -t build --parallel 2
        pnpm nx affected -t test --parallel 2 -- --ci --coverage --verbose --runInBand

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
      node-version: 16
      pnpm-version: 8

  codecov:
    name: CodeCov
    uses: ./.github/workflows/codecov.yml
    needs:
      - main
